name: tic_tac_toe
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
# dependencies:
  # tic_tac_toe:
    # path: /Users/dzamalabsaidov/vsCodeProjects/tic_tac_toe_project/lib/src/tic_tac_toe.dart
    # publish_to: none

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
